## Deploy/Update configuration files and scripts on client(gerrit) servers
## usage:
## 	1. cd path/to/environments
## 	2. ansible-playbook -e target_host=<IP> ../deploy_monitoring.yml

- hosts: "{{ target_host }}"
  gather_facts: no
  roles:
  - monitoring-config
  - monitoring-restart
