---

## This playbook is for auto install git
## prerequisite: ssh can login target instance and hosts inventory have instance information
## How to run:		
##	cd ~/ansible_deploy/environments
##      ansible-playbook -e target_host='<IP>' ../git.yml 

- hosts: "{{ target_host }}"
  roles:
  - common
  - git
