---

## This playbook is for auto install jdk
## prerequisite: ssh can login target instance and hosts inventory have instance information
## How to run:
##      cd ~/ansible_deploy/environments
##      ansible-playbook -e target_host='<IP>' ../jre.yml

- hosts: "{{ target_host }}"
  roles:
  - common
  - jre
